// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvhBvn3iqpXf-Kg24z7fIwcnj1LxHYvhI',
    appId: '1:1052567801942:web:8eff697782c79884cf2bf7',
    messagingSenderId: '1052567801942',
    projectId: 'flutter-cms-demo',
    authDomain: 'flutter-cms-demo.firebaseapp.com',
    databaseURL: 'https://flutter-cms-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cms-demo.appspot.com',
    measurementId: 'G-285S7HCQHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9uxC3vvRqAdVDu7GUQXHDxweHiTiKZXM',
    appId: '1:1052567801942:android:bb2745fec383876fcf2bf7',
    messagingSenderId: '1052567801942',
    projectId: 'flutter-cms-demo',
    databaseURL: 'https://flutter-cms-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cms-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DS3vXPRzEfnMkI17hV9gowHkk2plNkI',
    appId: '1:1052567801942:ios:a9888ccbb4e96c91cf2bf7',
    messagingSenderId: '1052567801942',
    projectId: 'flutter-cms-demo',
    databaseURL: 'https://flutter-cms-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cms-demo.appspot.com',
    iosClientId: '1052567801942-q0j90iofpk3mn2lk2ulg4jt6rcn7aibo.apps.googleusercontent.com',
    iosBundleId: 'com.gamotan.fluttercms.flutterCms',
  );
}
